[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=MMT -e 'Custom branding name for YouTube' -OappName=YouTube -e 'Custom header for YouTube' -OcustomHeader=Premium"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=MMT -e 'Custom branding name for YouTube Music' -OappNameNotification=Music -e 'Custom header for YouTube Music' -OcustomHeader=Teaqaria
"
